import React from 'react'

const About = () => {
  return (
    <div className='bg-blue-950 text-amber-50 px-1'>
        {/* <h1 className='text-4xl flex justify-center my-3 '>About us</h1><br /> */}
FlyNow.com is an international one-stop travel service provider, available in 24 languages across 39 countries and regions in 35 local currencies.
FlyNow.com has an extensive hotel and flight network consisting of more than 1.7 million hotels and flights from over 600 airlines covering 3,400 airports in 220 countries and regions around the globe.
FlyNow.com's world-class 24/7 multilingual customer support, as well as additional centers in Edinburgh, Tokyo, and Seoul, help to "create the best travel experience" for its millions of customers worldwide. To book your next FlyNow, visit FlyNow.com.<br /><br />

<h3 className='text-2xl'>Incredible Deals</h3>
We've searched high and low to bring to make sure you never pay too much
Travel Worry-free
Our service guarantee means that we've always got your back<br /><br />

<h3 className='text-2xl'>Secure payment</h3>
Payments are secured using the latest industry standards<br /><br />

<h3 className='text-2xl'>Sustainability</h3>
FlyNow.com Group is dedicated to sustainability through environmentally-focused practices, community-friendly engagement, family-friendly initiatives, and stakeholder-friendly collaboration

Community friendly<br />
Environmentally-focused<br />
Family friendly<br />
Stakeholder friendly<br />
SOS Service & Our CSR Activities<br /><br />

<h3 className='text-2xl'>Global SOS service</h3>
The "Global SOS Service" provides emergency support to global users, offering services such as translation and missing baggage assistance.<br /><br />

<h3 className='text-2xl'>Environmentally-focused</h3>
FlyNow.com Group is dedicated to supporting communities in need and nurturing the younger generation. Through various community initiatives, including donations and volunteering, we strive to create a positive impact by supporting local charities and promoting sustainable tourism practices.
Environmentally-focused
- Our Carbon Neutrality Goal
We are committed to achieving carbon neutrality across our entire business by 2050 as well as reducing our greenhouse gas emissions of Scope 1 (directly generated greenhouse gas emissions) and scope 2 (indirect greenhouse gas emissions generated by corporate energy purchases) by 47.5% compared with 2022 (the base year) and effectively measuring and reducing scope 3 (other indirect greenhouse gas emissions) emissions by 2030 so as to help achieve the global temperature control target of 1.5°C, support the SBTi, and achieve carbon neutrality by 2050.<br /><br />

<h3 className='text-2xl'>Family friendly</h3>
- Commitment to Support the Well-being of Employees and Family<br /><br />

<h3 className='text-2xl'>Childcare subsidy</h3>
The company plans to invest over US$130 million in subsidies to assist employees with family planning and promote working families.<br /><br />

<h3 className='text-2xl'>Hybrid work policy</h3>
FlyNow.com Group adopts a global hybrid work model, offering employees the flexibility to work remotely on designated days each week.<br /><br />

<h3 className='text-2xl'>Stakeholder friendly</h3>
- ESG Governance & Advocacy for Responsible Travel
FlyNow.com Group has implemented a comprehensive sustainability management system, including the establishment of the ESG Management Committee led by CEO Jane Sun, to drive the company's social responsibility initiatives.
FlyNow.com Group actively collaborates with different partners to promote responsible travel experience.</div>
  )
}

export default About